function x=main_newalgorithm2(y,lambda) 
	%+ centering removed, for any (n_1,n_2) contain in formulation
	Nbiter= 500;
tau = 0.99/10;
	sigma = 0.99/10;
	mu = 1;
%	imwrite(y,'y.tif');
		opD = @(x) cat(3,[diff(x,1,1);zeros(1,size(x,2))],[diff(x,1,2) zeros(size(x,1),1)], [[x(2:end,2:end) ; x(end,1:end-1)] x(:,end)]-x, [x(1,:); [x(1:end-1,2:end)  x(2:end,end)]]-x);
	opDadj = @(u) [zeros(1,size(u,2)); u(1:end-1,:,1)]-[u(1:end-1,:,1); zeros(1,size(u,2))]+...
    [zeros(size(u,1),1) u(:,1:end-1,2)]-[u(:,1:end-1,2) zeros(size(u,1),1)]+...
    [zeros(1,size(u,2));[zeros(size(u,1)-1,1) u(1:end-1,1:end-1,3)]]-[[u(1:end-1,1:end-1,3) zeros(size(u,1)-1,1)]; zeros(1,size(u,2))]+...
    [[zeros(size(u,1)-1,1) u(2:end,1:end-1,4)]; zeros(1,size(u,2))]-[zeros(1,size(u,2));[u(2:end,1:end-1,4) zeros(size(u,1)-1,1)]];
    prox_mu_tau_f = @(x) (x+mu*tau*y)/(1+mu*tau);
	prox_mu_sigma_g = @(t) t-bsxfun(@rdivide, t, max(sqrt(sum(t.^2,3))/(lambda*mu*sigma),1));
	x = y;
	u = zeros([size(x) 4]);
	v = zeros([size(y) 4 3]);
	%fprintf('0 %f\n',lambda*sum(sum(sum(sqrt(sum(v.^2,3))))));
	for iter = 1:Nbiter
		x = prox_mu_tau_f(x+tau*opDadj(-opD(x)+opLadj(v)-mu*u));
		v = prox_mu_sigma_g(v-sigma*opL(-opD(x)+opLadj(v)-mu*u));
		u = u-(-opD(x)+opLadj(v))/mu;
% 		if mod(iter,40)==0
% 			%we display the primal and dual cost functions, which reach equal values at convergence
% 			fprintf('%d %f %f\n',iter,sum(sum((x-y).^2))/2+lambda*sum(sum(sum(sqrt(sum(v.^2,3))))),...
% 				-sum(sum((y-opDadj(u)).^2-y.^2))/2);
% 			figure(2);
% 			imshow(x);
% 			colormap flag
% 			drawnow
% 		end
	end
% 	figure(2);
% 	imshow(x);
% 	colormap gray
%	imwrite(x,'x_proposed.tif');
end
function t = opL(u)
	[height,width,d]=size(u);
	t=zeros(height,width,4,3);
    t(:,:,1,1)=u(:,:,1); 
	t(:,:,2,1)=(u(:,:,2)+...
        [zeros(height,1) u(:,1:end-1,2)]+...
        [u(2:end,:,2); zeros(1,width)]+...
        [[zeros(height-1,1) u(2:end,1:end-1,2)]; zeros(1,width)])/4; 
	t(:,:,3,1)=(u(:,:,3)+...
        [zeros(height,1) u(:,1:end-1,3)])/2;
    t(:,:,4,1)=([u(2:end,:,4); zeros(1,width)]+...
        u(:,:,4)+[[zeros(height-1,1) u(2:end,1:end-1,4)]; zeros(1,width)]+...
        [u(3:end,:,4); zeros(2,width)]+...
        [zeros(height,1) [u(3:end,1:end-1,4);zeros(2,width-1)]]+...
        [zeros(height,1) u(:,1:end-1,4)])/6;
    t(:,:,2,2)=u(:,:,2);
	t(:,:,1,2)=(u(:,:,1)+...
        [zeros(1,width);u(1:end-1,:,1)]+...
        [u(:,2:end,1) zeros(height,1)]+...
        [zeros(1,width);[u(1:end-1,2:end,1) zeros(height-1,1)]])/4; 
    t(:,:,3,2) = (u(:,:,3)+[zeros(1,width);u(1:end-1,:,3)])/2; 
    t(:,:,4,2)=(u(:,:,4)+[u(2:end,:,4); zeros(1,width)])/2;
    t(end,1:end-1,4,2)=(u(end,1:end-1,4))/2;
	t(:,:,1,3) = (u(:,:,1)+[zeros(1,width);u(1:end-1,:,1)])/2;
	t(:,:,2,3) = (u(:,:,2)+[zeros(height,1) u(:,1:end-1,2)])/2; 
    t(:,:,3,3) =1/4*(u(:,:,3)+...
        [zeros(1,width) ; u(1:end-1,:,3)]+...
        [zeros(height,1) u(:,1:end-1,3)]+...
        [zeros(1,width);...
         [zeros(height-1,1) u(1:end-1,1:end-1,3)]]);
  	t(:,:,4,3)=(u(:,:,4)+...
        [u(2:end,:,4); zeros(1,width)]+...
        [zeros(height,1) u(:,1:end-1,4)]+...
                [[zeros(height-1,1) u(2:end,1:end-1,4)]; zeros(1,width)])/4; 
    end

function u = opLadj(t)
	[height,width,d,c]=size(t);
	u=zeros(height,width,4);
		[height,width,d,c]=size(t);
	u(:,:,1)=t(:,:,1,1)+...
        (t(:,:,1,2)+...
        [t(2:end,:,1,2); zeros(1,width)]+...
	[zeros(height,1) t(:,1:end-1,1,2)]+...
    [[zeros(height-1,1) t(2:end,1:end-1,1,2)];zeros(1,width)])/4+...
    (t(:,:,1,3)+[t(2:end,:,1,3); zeros(1,width)])/2;

u(:,:,2)=t(:,:,2,2)+...
    (t(:,:,2,1)+...
    [t(:,2:end,2,1) zeros(height,1)]+...
	[zeros(1,width); t(1:end-1,:,2,1)]+...
    [zeros(1,width); [t(1:end-1,2:end,2,1) zeros(height-1,1)]])/4+...
    (t(:,:,2,3)+[t(:,2:end,2,3) zeros(height,1)])/2;
    u(:,:,3)=(t(:,:,3,1)+...
        [t(:,2:end,3,1) zeros(height,1)])/2+...
     (t(:,:,3,2)+...
     [t(2:end,:,3,2); zeros(1,width)])/2+...
     (t(:,:,3,3)+...
     [t(2:end,:,3,3); zeros(1,width)]+...
     [t(:,2:end,3,3) zeros(height,1)]+...
     [[t(2:end,2:end,3,3) zeros(height-1,1)]; zeros(1,width)])/4;
 u(:,:,4)=1/6*(t(:,:,4,1)+[zeros(1,width); t(1:end-1,:,4,1) ]+...
     [[zeros(1,width-1); t(1:end-1,2:end,4,1)] zeros(height,1)]+...
     [zeros(2,width); t(1:end-2,:,4,1)]+...
     [zeros(2,width);[t(1:end-2,2:end,4,1) zeros(height-2,1)]]+...
     [t(:,2:end,4,1) zeros(height,1)])+...
     1/2*(t(:,:,4,2)+[zeros(1,width); t(1:end-1,:,4,2)])+...
     1/4*(t(:,:,4,3)+[zeros(1,width); t(1:end-1,:,4,3)]+...
     [ t(:,2:end,4,3) zeros(height,1)]+...
     [ [zeros(1,width-1); t(1:end-1,2:end,4,3)] zeros(height,1)]);
end